#!/bin/sh

# chkconfig: 2345 80 30
# description: Hydra Services
# processname: hydra


#========================================
#======= CONFIGURATION PARAMETERS =======
#========================================
NODE=/usr/local/bin/node          # path to node 
PYTHON_PATH=/usr/bin/             # path to python
PYTHON=python                     # python binary      
SRC_HOME=/home/igz/git/hydra/src  # route to hydra source code
ENVIROMENT=local                  # environment
CLIENT_PORT=7001                  # client api port
SERVER_PORT=7002                  # server api port
APP_MAN_PORT=7777                 # app manager port
#-----------------------------------------

start() {
  echo -n "Starting Hydra processes: "
  ulimit -n 999999
  cd ${SRC_HOME}
  echo 
  nohup ${NODE} ./client_api/app/main.js --port=${CLIENT_PORT} --env=${ENVIROMENT} >/dev/null 2>/dev/null &
	nohup ${PYTHON_PATH}${PYTHON} ./app_manager/app_manager_info_server.py localhost ${CLIENT_PORT} 0.0.0.0 ${APP_MAN_PORT} $! >/dev/null 2>/dev/null &
	nohup ${NODE} ./server_api/app/main.js --port=${SERVER_PORT} --env=${ENVIROMENT} >/dev/null 2>/dev/null &
	cd ./app_manager
	nohup ${PYTHON_PATH}${PYTHON} ./app_manager.py -c app_manager.cfg >/dev/null 2>/dev/null &
  echo "done."
}

stop() {
     echo -n "Shutting down all Hydra services: "
     killall -9 node
     killall -9 ${PYTHON}
     echo "done."
}

case "$1" in
     start)
          start
          ;;

     stop)
          stop
          ;;

#     restart)
#          stop
#          sleep 5
#          start
#          ;;

     *)
          echo "Usage: $0 {start|stop|restart}"
esac
exit 0